'''
Created on 2012-11-5

@author: Administrator
file: GeneratorFunctions.py
description: GeneratorFunctions.py demonstrate use Generator function, a special function that uses the functional concept
and improve the effeciency of data generation.

in general, the generator is a mechanism that defer some exeuction until it is actually used. There is a built-in state machine to maintain the state when the collection is visited. 
also, you can treat the sequence generated by generator a normal sequence, except that it is executed defered

'''
def four():
    x = 0
    while x < 4:
        print("In generator , x = ", x)
        yield x
        x += 1

def use_of_generator():
    for i in four():
        print(i)   
    print("*** you can treat the generator as input as the collection ")     
    x = 2 in four()
    x = 5 in four()

if __name__ == '__main__':
    for i in four():
        print(i)