USE [Unity_dev1]
GO

/****** Object:  Table [dbo].[CASH_TRADE]    Script Date: 01/17/2014 18:53:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASH_TRADE](
	[latest] [bit] NOT NULL,
	[Account2ID] [nvarchar](256) NULL,
	[Account2LegalEntity] [nvarchar](256) NULL,
	[Account2Name] [nvarchar](256) NULL,
	[Account2NTAPS] [nvarchar](256) NULL,
	[Account2RDMID] [nvarchar](256) NULL,
	[AccountID] [nvarchar](256) NULL,
	[AccountLegalEntity] [nvarchar](256) NULL,
	[AccountName] [nvarchar](256) NULL,
	[AccountNTAPS] [nvarchar](256) NULL,
	[AccountRDMID] [nvarchar](256) NULL,
	[AccruedInterest] [decimal](38, 6) NULL,
	[AccruedInterestIsOverridden] [nvarchar](256) NULL,
	[AnalyticsStatus] [nvarchar](256) NULL,
	[ApprovalBy] [nvarchar](256) NULL,
	[ApprovalStatus] [nvarchar](256) NULL,
	[AssetClass] [nvarchar](256) NULL,
	[BenchmarkCusip] [nvarchar](256) NULL,
	[BenchmarkIsin] [nvarchar](256) NULL,
	[BenchmarkSecurityId] [nvarchar](256) NULL,
	[BenchmarkSecurityName] [nvarchar](256) NULL,
	[BenchmarkSpread] [decimal](38, 6) NULL,
	[BookFOBK] [nvarchar](256) NULL,
	[BookID] [nvarchar](256) NULL,
	[BookIDType] [nvarchar](256) NULL,
	[BookName] [nvarchar](256) NULL,
	[BookNTAPS] [nvarchar](256) NULL,
	[BookRegion] [nvarchar](256) NULL,
	[BookSTBK] [nvarchar](256) NULL,
	[Broker] [nvarchar](256) NULL,
	[BuySell] [nvarchar](256) NULL,
	[ClearingHouse] [nvarchar](256) NULL,
	[ClusterTimestamp] [datetime] NULL,
	[Comment] [nvarchar](256) NULL,
	[ContraBookId] [nvarchar](256) NULL,
	[ContraBookIdType] [nvarchar](256) NULL,
	[ContraBookName] [nvarchar](256) NULL,
	[ContraBookNTAPS] [nvarchar](256) NULL,
	[ContraBookRegion] [nvarchar](256) NULL,
	[ContraBookSTBK] [nvarchar](256) NULL,
	[ContraLegalEntity] [nvarchar](256) NULL,
	[CounterpartyID] [nvarchar](256) NULL,
	[CounterpartyIDType] [nvarchar](256) NULL,
	[CounterpartyLegalEntity] [nvarchar](256) NULL,
	[CounterpartyLVCC] [nvarchar](256) NULL,
	[CounterpartyMPID] [nvarchar](256) NULL,
	[CounterpartyName] [nvarchar](256) NULL,
	[CounterpartyNTAPS] [nvarchar](256) NULL,
	[CounterpartyRDMID] [nvarchar](256) NULL,
	[CounterpartySubType] [nvarchar](256) NULL,
	[CounterpartyTotoroName] [nvarchar](256) NULL,
	[Coupon] [decimal](38, 6) NULL,
	[Created] [datetime] NULL,
	[Currency] [nvarchar](256) NULL,
	[CurrentFactor] [decimal](38, 6) NULL,
	[DestinationError] [nvarchar](256) NULL,
	[DestinationID] [nvarchar](256) NULL,
	[DestinationStatus] [nvarchar](256) NULL,
	[DestinationSystem] [nvarchar](256) NULL,
	[DestinationVersion] [nvarchar](256) NULL,
	[Discount] [decimal](38, 6) NULL,
	[DoNotReportToTrace] [nvarchar](256) NULL,
	[DoNotSendToDownStream] [nvarchar](256) NULL,
	[EnteredBy] [nvarchar](256) NULL,
	[EntryDateTime] [datetime] NULL,
	[EntrySystem] [nvarchar](256) NULL,
	[EntrySystemId] [nvarchar](256) NULL,
	[EntrySystemVersion] [nvarchar](256) NULL,
	[EventID] [nvarchar](256) NULL,
	[EventType] [nvarchar](256) NULL,
	[ExecutionDateTime] [datetime] NULL,
	[ExternalOrderId] [nvarchar](256) NULL,
	[ExternalSubsystem] [nvarchar](256) NULL,
	[ExternalSystem] [nvarchar](256) NULL,
	[ExternalSystemId] [nvarchar](256) NULL,
	[LastDeliveryDate] [datetime] NULL,
	[LegalEntity] [nvarchar](256) NULL,
	[Location] [nvarchar](256) NULL,
	[MatchStatus] [nvarchar](256) NULL,
	[MatchStatusCATS] [nvarchar](256) NULL,
	[MatchTradeId] [nvarchar](256) NULL,
	[Maturity] [datetime] NULL,
	[Notional] [decimal](38, 6) NULL,
	[NumContracts] [decimal](38, 6) NULL,
	[Perpetual] [nvarchar](256) NULL,
	[PriceFormat] [nvarchar](256) NULL,
	[PriceTraded] [decimal](38, 6) NULL,
	[PriceType] [nvarchar](256) NULL,
	[Quantity] [decimal](38, 6) NULL,
	[ReferenceDataStatus] [nvarchar](256) NULL,
	[RFQBookID] [nvarchar](256) NULL,
	[RFQBookIDType] [nvarchar](256) NULL,
	[RFQBookSTBK] [nvarchar](256) NULL,
	[RiskKey] [nvarchar](256) NULL,
	[SalesCommissionCurrency] [nvarchar](256) NULL,
	[SalesCommissionSubType] [nvarchar](256) NULL,
	[SalesCommissionTotal] [decimal](38, 6) NULL,
	[SalesCredit] [decimal](38, 6) NULL,
	[SalesCreditAdditional] [decimal](38, 6) NULL,
	[SalesCreditIsZero] [nvarchar](256) NULL,
	[SalesID] [nvarchar](256) NULL,
	[SalesIDType] [nvarchar](256) NULL,
	[Salesman] [nvarchar](256) NULL,
	[SalesmanC3SC] [nvarchar](256) NULL,
	[SalesMarkup] [decimal](38, 6) NULL,
	[SalesMatchStatus] [nvarchar](256) NULL,
	[Seasoned] [nvarchar](256) NULL,
	[SecurityBBID] [nvarchar](256) NULL,
	[SecurityBBPK] [nvarchar](256) NULL,
	[SecurityBPKY] [nvarchar](256) NULL,
	[SecurityCUSIP] [nvarchar](256) NULL,
	[SecurityID] [nvarchar](256) NULL,
	[SecurityIDType] [nvarchar](256) NULL,
	[SecurityISIN] [nvarchar](256) NULL,
	[SecurityName] [nvarchar](256) NULL,
	[SecurityPDP] [nvarchar](256) NULL,
	[SecurityRIC] [nvarchar](256) NULL,
	[SecurityTotoroName] [nvarchar](256) NULL,
	[SecurityType] [nvarchar](256) NULL,
	[Series] [nvarchar](256) NULL,
	[SettlementCurrency] [nvarchar](256) NULL,
	[SettlementError] [nvarchar](256) NULL,
	[SettlementFXRate] [decimal](38, 6) NULL,
	[SettlementID] [nvarchar](256) NULL,
	[SettlementStatus] [nvarchar](256) NULL,
	[SettlementSystem] [nvarchar](256) NULL,
	[SettlementVersion] [nvarchar](256) NULL,
	[SourceSecurityID] [nvarchar](256) NULL,
	[SourceSystem] [nvarchar](256) NULL,
	[SuggestedMatch] [nvarchar](256) NULL,
	[Ticker] [nvarchar](256) NULL,
	[TicketClass] [nvarchar](256) NULL,
	[TicketCompletionStatus] [nvarchar](256) NULL,
	[TicketID] [nvarchar](256) NULL,
	[TicketSubType] [nvarchar](256) NULL,
	[TicketType] [nvarchar](256) NULL,
	[Timestamp] [datetime] NULL,
	[TraceEligible] [nvarchar](256) NULL,
	[TraceMarketIndicator] [nvarchar](256) NULL,
	[TracePriceOverride] [nvarchar](256) NULL,
	[TraceSpecialPrice] [nvarchar](256) NULL,
	[TraceWeightedAvgPrice] [nvarchar](256) NULL,
	[TradeDate] [datetime] NULL,
	[TradeGroupId] [nvarchar](256) NULL,
	[TradeId] [nvarchar](40) NULL,
	[TradeOperation] [nvarchar](256) NULL,
	[Trader] [nvarchar](256) NULL,
	[TraderC3DC] [nvarchar](256) NULL,
	[TraderSystem] [nvarchar](256) NULL,
	[TradeSettleDate] [datetime] NULL,
	[TradeSettleDays] [nvarchar](256) NULL,
	[TradeSource] [nvarchar](256) NULL,
	[TradeStateVersion] [int] NULL,
	[TradeVersion] [int] NULL,
	[Updated] [datetime] NULL,
	[ValuationFunction] [nvarchar](256) NULL,
	[WashAccount2ID] [nvarchar](256) NULL,
	[WashAccount2LegalEntity] [nvarchar](256) NULL,
	[WashAccount2Name] [nvarchar](256) NULL,
	[WashAccount2NTAPS] [nvarchar](256) NULL,
	[WashAccount2RDMID] [nvarchar](256) NULL,
	[WashAccountID] [nvarchar](256) NULL,
	[WashAccountLegalEntity] [nvarchar](256) NULL,
	[WashAccountName] [nvarchar](256) NULL,
	[WashAccountNTAPS] [nvarchar](256) NULL,
	[WashAccountRDMID] [nvarchar](256) NULL,
	[WashBook2FOBK] [nvarchar](256) NULL,
	[WashBook2ID] [nvarchar](256) NULL,
	[WashBook2LegalEntity] [nvarchar](256) NULL,
	[WashBook2Name] [nvarchar](256) NULL,
	[WashBook2NTAPS] [nvarchar](256) NULL,
	[WashBook2STBK] [nvarchar](256) NULL,
	[WashBookFOBK] [nvarchar](256) NULL,
	[WashBookID] [nvarchar](256) NULL,
	[WashBookLegalEntity] [nvarchar](256) NULL,
	[WashBookName] [nvarchar](256) NULL,
	[WashBookNTAPS] [nvarchar](256) NULL,
	[WashBookSTBK] [nvarchar](256) NULL,
	[WashParentTradeId] [nvarchar](256) NULL,
	[Yield] [decimal](38, 6) NULL,
	[BrokerageAmount] [decimal](38, 6) NULL,
	[BrokerageCommissionClose] [decimal](38, 6) NULL,
	[BrokerageCommissionOpen] [decimal](38, 6) NULL,
	[BrokerageCurrency] [nvarchar](256) NULL,
	[BrokerGiveUp] [nvarchar](256) NULL,
	[CallOrPut] [nvarchar](256) NULL,
	[EntrySubsystem] [nvarchar](256) NULL,
	[Exchange] [nvarchar](256) NULL,
	[SalesmanName] [nvarchar](256) NULL,
	[SecurityMeigara] [nvarchar](256) NULL,
	[TraderName] [nvarchar](256) NULL,
	[AccruedInterestType] [nvarchar](256) NULL,
	[BrokerageAmountBakedIn] [nvarchar](256) NULL,
	[DepositCondition] [nvarchar](256) NULL,
	[NetPrincipal] [decimal](38, 6) NULL,
	[PriceStripped] [decimal](38, 6) NULL,
	[TaxableIndicator] [nvarchar](256) NULL,
	[AtsukaishaCode] [nvarchar](256) NULL,
	[BaseCommissionRate] [decimal](38, 6) NULL,
	[BasePrice] [decimal](38, 6) NULL,
	[BasePriceType] [nvarchar](256) NULL,
	[BaseYield] [decimal](38, 6) NULL,
	[BaseYieldType] [nvarchar](256) NULL,
	[BranchSalesman] [nvarchar](256) NULL,
	[ConversionFactor] [decimal](38, 6) NULL,
	[ExerciseEndDateTime] [datetime] NULL,
	[ExerciseStartDate] [datetime] NULL,
	[FailBuyIn] [nvarchar](256) NULL,
	[FinalFuturesPrice] [decimal](38, 6) NULL,
	[FITSCounterpartyClass] [nvarchar](256) NULL,
	[FXCommissionRate] [decimal](38, 6) NULL,
	[FXCommissionTotal] [decimal](38, 6) NULL,
	[FXTradeId] [nvarchar](256) NULL,
	[JPYAccruedInterest] [decimal](38, 6) NULL,
	[JPYFXRate] [decimal](38, 6) NULL,
	[JPYFXType] [nvarchar](256) NULL,
	[JPYNetPrincipal] [decimal](38, 6) NULL,
	[JPYPrincipal] [decimal](38, 6) NULL,
	[LastClosingPrice] [decimal](38, 6) NULL,
	[MarketIndicator] [nvarchar](256) NULL,
	[NextCouponDate] [datetime] NULL,
	[OptionType] [nvarchar](256) NULL,
	[PrevCouponDate] [datetime] NULL,
	[PriceTradedType] [nvarchar](256) NULL,
	[PrincipalIsOverridden] [nvarchar](256) NULL,
	[Reserved] [nvarchar](256) NULL,
	[SettlementAccountType] [nvarchar](256) NULL,
	[TotalCommissionAmount] [decimal](38, 6) NULL,
	[TotalCommissionRate] [decimal](38, 6) NULL,
	[TradeModelIsJapan] [nvarchar](256) NULL,
	[YieldType] [nvarchar](256) NULL,
	[DualCurrencyFXRate] [decimal](38, 6) NULL,
	[DualCurrencyNetPrincipal] [decimal](38, 6) NULL,
	[Principal] [decimal](38, 6) NULL,
	[SalesmanNameKanji] [nvarchar](256) NULL,
	[AccrualAmount] [decimal](38, 6) NULL,
	[AmendmentReason] [nvarchar](256) NULL,
	[OriginalTradeId] [nvarchar](256) NULL,
	[PackageEventCount] [bigint] NULL,
	[PackageEventId] [nvarchar](256) NULL,
	[PackageId] [nvarchar](256) NULL,
	[PreviousTradeId] [nvarchar](256) NULL,
	[PriceTradedClean] [decimal](38, 6) NULL,
	[PrincipalClean] [decimal](38, 6) NULL,
	[YieldCompound] [decimal](38, 6) NULL,
	[YieldSimple] [decimal](38, 6) NULL,
	[AccruedDays] [bigint] NULL,
	[EventSubType] [nvarchar](256) NULL,
	[ForeignBondIsTaxable] [nvarchar](256) NULL,
	[Strike] [decimal](38, 6) NULL,
	[UnderlyingDeliveryDays] [bigint] NULL
) ON [PRIMARY]

GO


